name: Android CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    
    steps:
    # https://github.com/styfle/cancel-workflow-action#usage
    - name: Cancel Previous Runs
      uses: styfle/cancel-workflow-action@0.11.0
      with:
        access_token: ${{ secrets.GITHUB_TOKEN }}
          
    - uses: actions/checkout@v3
    
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle
      
    # https://github.com/ruby/setup-ruby#single-job
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.0'
        bundler-cache: true
        
    - name: Install Danger
      run: |
        gem install danger:9.2.0
        gem install danger-chikuwa
        
    - name: Create local.properties
      env:
        GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        echo "GITHUB_ACCESS_TOKEN=$GITHUB_ACCESS_TOKEN" >> local.properties

   # - name: Runs lint on the default variant.
   #   run: ./gradlew lint
    
    - name: Run unit tests for all variants.
      run: ./gradlew test

    - name: Build tasks (Assemble main outputs for all the variants.)
      run: |
        ./gradlew assemble 2>&1 | tee build.log
      # continue-on-error: true
      
    - name: Run Danger
      run: danger --remove-previous-comments
      env:
        DANGER_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    # https://github.com/android/nowinandroid/blob/main/.github/workflows/Build.yaml
    - name: Upload build outputs (APKs)
      uses: actions/upload-artifact@v3
      with:
        name: build-outputs
        path: app/build/outputs

    - name: Upload build reports
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: build-reports
        path: app/build/reports
