name: Android CI

on:
  push:
    branches: [ "main", "develop", /^release\-.*$/ ]
  pull_request:
    branches: [ "main", "develop", /^release\-.*$/ ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.6
        bundler-cache: true
    - name: Install Danger
      run: |
        gem install danger:8.4.2
        gem install danger-chikuwa
    - name: Build
      run: ./gradlew assembleDebug 2>&1 | tee build.log
      continue-on-error: true
    - name: Run Danger
      run: danger --remove-previous-comments
      env:
        DANGER_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: test with Gradle
      run: ./gradlew test
